

export const SELECTED_PRODUCT = 'SELECTED_PRODUCT';
export const PRODUCT_BUY = 'PRODUCT_BUY';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const DELETE_ALL = 'ADD_TO_CART';
export const ADD_QUANTITY = 'ADD_QUANTITY';
export const REMOVE_QUANTITY = 'REMOVE_QUANTITY';